### PR TITLE
Finding Hyperlinks within Collection on Pages with Certain Keyword

### PR DESCRIPTION
**Pull request by SinghGursimran**
Extract hyperlinks within a collection filtered on pages containing a particular keyword (case insensitive) using df.

```scala

import io.archivesunleashed._
import io.archivesunleashed.df._

val result = udf((vs: Seq[Any]) => vs(0).toString.split(",")(1))

val df= RecordLoader.loadArchives("src/test/resources/warc/example.warc.gz", sc).extractValidPagesDF()
.select(     RemovePrefixWWW(ExtractDomain($"url")).as("Domain"),
  	        $"url".as("url"),
  	        $"crawl_date",
  	        explode_outer(ExtractLinks($"url",$"content")).as("link")
  	  )
.filter(lower($"content").contains("internet")) //filtered on keyword "internet"

df.select($"url",$"Domain",$"crawl_date",result(array($"link")).as("destination_page"))
.write
.option("header","true")
.csv("filtered_results/")

```
#238 

Returns a csv file with URL, Domain, crawl_date, and destination_page.

### CODE REVIEW

**Comment by lintool** [comment]
hey @ruebot is this something that should be encoded in a test case while we're at it?

**Comment by lintool** [comment]
@ruebot add a separate test case that explicitly include filtering? Maybe not. I dunno.

**Comment by ianmilligan1** [comment]
@ruebot Looks perfect to me - and I love the sample results with "keystone" leading to David Suzuki. Thanks @SinghGursimran, great work.

**Comment by SinghGursimran** [comment]
> Yeah, we could add a new test that add `filter` or just add a `filter` to https://github.com/archivesunleashed/aut/blob/e32ae17c55740c6c6adc177d42690b39fa6321dd/src/test/scala/io/archivesunleashed/matchbox/ExtractLinksTest.scala if that's what you're thinking.
> 
> ...and if that's the case, @SinghGursimran, want to update the PR with an updated test?

**Pull request merged**
