### PR TITLE
Gexf Fixes & StringUtil Functions #172

### PR DESCRIPTION
**Pull request by greebie**
- add hash for ids in gexf
- add escaper for xml
- move hash udf to string utils
- improve output for gexf

**The title of this pull-request should be a brief description of what the pull-request fixes/improves/changes. Ideally 50 characters or less.**

* * *

**GitHub issue(s)**:

If you are responding to an issue, please mention their numbers below.

#172

# What does this Pull Request do?

- Provides udf for escaping non-xml friendly characters.
- Move md5 hash function to StringUtils
- Fixes Gexf problems due to faulty data

# How should this be tested?

Broken outputs should be tested in Gephi.

# Additional Notes:

Simply adding &<> or " to a url output can suffice as a broken string.

# Interested parties

@ianmilligan1 

Thanks in advance for your help with the Archives Unleashed Toolkit!

### CODE REVIEW

**Comment by greebie** [comment]
I have not tested a broken output in the gexf yet.   But will confirm that it works from my end tonight.

**Comment by ianmilligan1** [comment]
A user is running a test using this branch too, so I will wait to hear outcomes before merging this PR - but all good on my end.

**Comment by cjer** [comment]
Finished my test run.
Ran successfully, no escaping issues or errors when importing to Gephi!
It did recognize duplicate edges that had to be merged. Is that expected behavior?

**Comment by greebie** [comment]
I had the same issue.  It *could* be related to the fact that some of the data has been corrupted and Gephi is doing a lovely job of figuring that out.  IMHO we are okay to merge, and add the bug as an issue for later, given that it's minor and I am unsure how hard it will be to figure out.

**Comment by cjer** [comment]
I could try some python munging on the gexf to trace the duplicates if you like

**Comment by ianmilligan1** [comment]
Sure. @cjer if you could take a quick look? Might as well see if it is relatively easy to fix before merging. If it's an involved fix, I agree that merging and opening up an issue makes sense.

**Comment by cjer** [comment]
Ok I think I got it. They're not duplicates if I consider the crawlDate. So I guess all is alright

**Comment by greebie** [comment]
I was looking at the inputs and outputs for the GraphML and GEXF.  It may be good in the future to provide more flexibility for attributes in the future, so it's good to track that!

**Comment by ianmilligan1** [comment]
OK thx @cjer! Are you happy with this then, @greebie, to merge?

**Comment by greebie** [comment]
Yes -- if you are good I am good.

**Pull request merged**
