### PR TITLE
Rename DF functions to be consistent with Python DF functions.

### PR DESCRIPTION
**Pull request by ruebot**
**GitHub issue(s)**: #366 

# What does this Pull Request do?

Rename DF functions to be consistent with Python DF functions.

# How should this be tested?

- TravisCI (unit tests) should take care of it.

# Additional Notes:

1. @lintool the only part of the issue I haven't resolved here is your proposal to move `WebArchive` to `RecordLoader.loadArchives` on the Python side. I don't believe we can have `RecordLoader.loadArchives` as an actual class name. So, should we change things in the other direction or both directions? I've been naming a `val` `warcs` a lot in my example. What if we did something like that? Or `webArchives` or `webarchives` ? Once we settle on something, I'll the PR out of draft.

2. There will be a **TONNE** of documentation updates to do. If I could get a hand there, that'd be super helpful. @SamFritz @ianmilligan1 that of any interest?

### CODE REVIEW

**Comment by ianmilligan1** [comment]
👀 

Looks like a great PR in progress, and agreed, the documentation will be heavy-ish lifting. I can help out if you give me discrete chunks of work (between parental leave, grant writing, admin, and some unfortunate university admin work coming up, my time is a bit limited, but many hands makes for light work).

**Comment by lintool** [comment]
@rubot I'm not wedded to perfect alignment between Scala DF and Pyspark DF at this point... perhaps we should just wait for #371?

I would rather do the refactoring incrementally... i.e., let's get this merged, start fixing docs, etc.

**Comment by ianmilligan1** [comment]
Great! @ruebot and I can maybe work together or the docs? When I have time I can start a branch or vice versa.

**Comment by ianmilligan1** [comment]
Sure, sounds good on updating the PR and going fro, there! I might be able to tackle some of this tomorrow, kids schedule permitting.

**Pull request merged**
