### PR TITLE
Add office document binary extraction.

### LINKED ISSUE #303: Spreadsheet binary object extraction
Using the [image extraction process](https://github.com/archivesunleashed/aut/pull/234) as a basis, our next set of binary object extractions will be documents. This issue is meant to focus specially on `xls`  `xlsx`, `ods`, and `csv`.

There may be a some tweaks to this depending on the outcome of #298.

### LINKED ISSUE #304: Doc binary object extraction
Using the [image extraction process](https://github.com/archivesunleashed/aut/pull/234) as a basis, our next set of binary object extractions will be documents. This issue is meant to focus specially on `doc`  `docx`, and `odt`.

There may be a some tweaks to this depending on the outcome of #298.

### LINKED ISSUE #305: Powerpoint binary object extraction
Using the [image extraction process](https://github.com/archivesunleashed/aut/pull/234) as a basis, our next set of binary object extractions will be documents. This issue is meant to focus specially on `ppt`  `pptx`, and `odp`.

There may be a some tweaks to this depending on the outcome of #298.

### PR DESCRIPTION
**Pull request by ruebot**
**GitHub issue(s)**:

- #303 
- #304 
- #305
- #322 

# What does this Pull Request do?

- Add WordProcessor DF and binary extraction
- Add Spreadsheets DF and binary extraction
- Add Presentation Program DF and binary extraction
- Add tests for new DF and binary extractions
- Add test fixture for new DF and binary extractions
- Resolves #303
- Resolves #304 
- Resolves #305
- Back out 39831c28ad3e9cd816c57294f08a13024c59dedf (We _might_ not have
to do this)

# How should this be tested?

- TravisCI
- I tested on the 10 GeoCities WARCs, [here](https://gist.github.com/ruebot/46dd2041d71dda26366f2f5b2817c6bf) is a whole bunch of info

```bash
$ rm -rf ~/.m2/repository/* && mvn clean install && rm -rf ~/.ivy2/* && time ~/bin/spark-2.4.3-bin-hadoop2.7/bin/spark-shell --master local\[10\] --driver-memory 35g --conf spark.network.timeout=10000000 --conf spark.executor.heartbeatInterval=600s --conf spark.driver.maxResultSize=4g --conf spark.serializer=org.apache.spark.serializer.KryoSerializer --conf spark.shuffle.compress=true --conf spark.rdd.compress=true --packages io.archivesunleashed:aut:0.17.1-SNAPSHOT -i ~/office-document-extraction.scala
```

```scala
import io.archivesunleashed._
import io.archivesunleashed.df._

val df_ss = RecordLoader.loadArchives("/home/nruest/Projects/au/sample-data/geocites/1/*gz", sc).extractSpreadsheetDetailsDF();
val res_ss = df_ss.select($"bytes", $"extension").saveToDisk("bytes", "/home/nruest/Projects/au/sample-data/306-307-test/spreadsheet", "extension")

val df_pp = RecordLoader.loadArchives("/home/nruest/Projects/au/sample-data/geocites/1/*gz", sc).extractPresentationProgramDetailsDF();
val res_pp = df_pp.select($"bytes", $"extension").saveToDisk("bytes", "/home/nruest/Projects/au/sample-data/306-307-test/presentation", "extension")

val df_word = RecordLoader.loadArchives("/home/nruest/Projects/au/sample-data/geocites/1/*gz", sc).extractWordProcessorDetailsDF();
val res_word = df_word.select($"bytes", $"extension").saveToDisk("bytes", "/home/nruest/Projects/au/sample-data/306-307-test/document", "extension")

sys.exit
```

# Additional Notes:

- Do we want to include plain text (txt) files in Word Processor?
- Is it work putting some NOT conditionals in these? Like `! r._1 == "text/html"` or `! r._1.startsWith("image/")`. Or, is it worth leaving some of this noise in there?

### CODE REVIEW

**Comment by ianmilligan1** [comment]
Will review in a few minutes!

Re:
>Do we want to include plain text (txt) files in Word Processor?

I think it'd probably make sense to include `txt` files. That said, if so, maybe we should consider renaming `extractWordProcessorDetailsDF` to something like `extractTextDocumentDetailsDF`? 

Or we could create a new one just for plain text files? 🤔

**Comment by jrwiebe** [comment]
I agree re. a separate method for plain text files.

**Comment by ianmilligan1** [comment]
Separate method sounds good to me too. Thanks, @ruebot !

**Comment by jrwiebe** [comment]
This looks good. It looks pretty familiar, as I had a branch addressing #303 and/or #304, but I got stymied by the dependency issue and seem to have lost that work (I probably messed up some git stuff locally and re-cloned `aut`). We could remove most of the ors and replace them with something like `documentMimes.contains(r._2)`, creating a corresponding list of mime types residing outside of the method definition, but I don't feel strongly about that.

I removed the classifier from the pom and the build went fine. For the record, the reason it didn't work for @ruebot (he already knows this) is that the CDN used by JitPack to serve the jars cached an older version of the file we need, so his build was not getting the shaded artifact.

**Comment by jrwiebe** [comment]
The false positives come from filtering on file extension. I think we could remove most of those, except for "tsv" and "csv".

**Comment by jrwiebe** [comment]
@ruebot You don't have a log of the failed tests, do you? I'm interested to know which files Tika failed to identify correctly, and what it identified them as (`application/octet-stream`?).

**Comment by jrwiebe** [comment]
@ruebot The unit tests failed when you weren't filtering on file extension because:
a) the word processor extractor was filtering on mime "text/rtf" instead of "application/rtf", and
b) the spreadsheet extractor doesn't detect CSV or TSV (CSV detection might be in the works, see [TIKA-2826](https://issues.apache.org/jira/browse/TIKA-2826)).

I pushed a fix to (a), and removed the rest of the file extension filtering from the word processor document extractor. For (b), I left in the filtering on CSV and TSV extensions, but removed the other formats. Now the tests pass.

BTW, should we add the dot before extensions when `endsWith`? Currently our spreadsheet filter, for example, would evaluate to true something like `http://example.com/fileformatsoftheages/csv`". Also, URLs could contain uppercase.

**Comment by jrwiebe** [comment]
@ruebot Go for it. I'm done with this for today.

**Comment by jrwiebe** [comment]
@ianmilligan1 @ruebot Revert this change (i.e., put the classifier back in). You guys are getting the cached tika-parsers JAR (see #345). This might break use of `--packages`, though.

**Comment by jrwiebe** [comment]
Try running [tika-app](https://www.apache.org/dyn/closer.cgi/tika/tika-app-1.22.jar) detect on those same files. 
```
java -jar tika /path/to/tika-app-1.22.jar -d [files]
```

**Comment by jrwiebe** [comment]
> Dealing with this Tika dependency thing over the last 6 months
> 
> tenor

Yup

**Comment by jrwiebe** [comment]
> hrm, if I test with that tika-parsers commit you added, things blow up after a while, and I get this error:
> 
> ```
> java.nio.file.FileSystemException: /tmp/apache-tika-4408340307210314122.tmp: Too many open files
> ```
> 
> ...with a whole lot of apache-tika-adfasdfasdfasdfdasw.tmp files in my `/tmp` dir.

I probably should have been `close()`-ing each TikaInputStream in `DetectMimeTypeTika`. I'll push this fix in a sec assuming it passes the build tests.

**Comment by jrwiebe** [comment]
There shouldn't be any difference in behaviour between the two tika-parsers artifacts. The only difference besides where they are downloaded from is that one has a classifier as part of its versioning.

**Comment by jrwiebe** [comment]
I ran a [variant](https://gist.github.com/jrwiebe/d7bfe3afb2b4ff995de1e478b0ea178c) of the above `office-document-extraction.scala` last night, built from [
8a124d3](https://github.com/archivesunleashed/aut/commit/8a124d33ea3bac0c2bb3c43acdd43310c39f5def). The script was something I had around from testing yesterday, so it was missing `extractTextFilesDetailsDF`. I ran it on `/tuna1/scratch/nruest/geocites/warcs/1/*.gz`. Is this the same sample you were using, @ruebot? 

This was on `tuna`, so the resources available were different, but it didn't blow up. It took about four hours.

#### Extraction stats:
```
jrwiebe@tuna:~$ ls office-extract-test/spreadsheet-*|wc -l
1291
jrwiebe@tuna:~$ ls office-extract-test/presentation-*|wc -l
2840
jrwiebe@tuna:~$ ls office-extract-test/document-*|wc -l
8732
jrwiebe@tuna:~$ ls office-extract-test/*|wc -l
12863
jrwiebe@tuna:~$ cat aut/office-document-extraction.time.txt 
real    168m19.665s
user    997m59.700s
sys 153m2.312s
```

**Pull request merged**
