### PR TITLE
fix #199: mime-type was incorrectly parsed from content-type when cha…

### LINKED ISSUE #199: keepValidPages incorrectly filters out pages with mime-type text/html followed by charset
Sometimes, the Content-Type header contains the charset, such as `text/html;charset=ISO-8859-1` for page http://www.patentbuddy.com/,
so the `keepValidPages` function does not work properly in those cases: it incorrectly filters out such pages.

More info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type

```
package io.archivesunleashed.spark.rdd
object RecordRDD extends java.io.Serializable {
    def keepValidPages(): RDD[ArchiveRecord] = {
      rdd.filter(r =>
        r.getCrawlDate != null
          && (r.getMimeType == "text/html"
          || r.getMimeType == "application/xhtml+xml"
          || r.getUrl.endsWith("htm")
          || r.getUrl.endsWith("html"))
          && !r.getUrl.endsWith("robots.txt"))
    }
```

### PR DESCRIPTION
**Pull request by dportabella**
fix #199: mime-type was incorrectly parsed from content-type when charset param exists

* * *

**GitHub issue(s)**:

If you are responding to an issue, please mention their numbers below.
#199 

# What does this Pull Request do?
Calling `WarcRecordUtils.getWarcResponseMimeType` with a header such as `Content-Type: text/html;charset=ISO-8859-1` should return `text/html`. However it was returning `text/html;charset=ISO-8859-1`. Also, the function `keepValidPages` was not working properly because of this.

This pull request fixes this issue.

# How should this be tested?
A unit test was added: `WarcLoaderTest.testContentTypeWithCharset`

# Additional Notes:

Any additional information that you think would be helpful when reviewing this PR.

Example:
* Does this change require documentation to be updated?
No

* Does this change add any new dependencies?
No

* Could this change or impact execution of existing code?
No

# Interested parties

Tag (@ mention) interested parties.

Thanks in advance for your help with the Archives Unleashed Toolkit!

### CODE REVIEW

**Comment by dportabella** [comment]
Line are limited to 80 characters? 😖
Ok, I fix this.
Then I create a new commit with `--amend`? 
or I delete this pull-request and I create a new one?

**Comment by dportabella** [comment]
done.

**Comment by greebie** [comment]
Thanks for being a contributor, @dportabella !

**Comment by dportabella** [comment]
welcome :)

**Pull request merged**
