### PR TITLE
make ArchiveRecord a trait

### PR DESCRIPTION
**Pull request by helgeho**
**The title of this pull-request should be a brief description of what the pull-request fixes/improves/changes. Ideally 50 characters or less.**

* * *

**GitHub issue(s)**:

If you are responding to an issue, please mention their numbers below.

* ex: #1
* ex: #2

# What does this Pull Request do?

A brief description of what the intended result of the Pull Request (PR) will be, what problem it solves, technical details, and any possible side effects.

Example:
* Changes x feature to such that y
* Added x
* Removed y

# How should this be tested?

A description of what steps someone could take to:
* Reproduce the problem you are fixing (if applicable)
* Test that the PR does what is intended.
* Please be as detailed as possible.
* Good testing instructions help get your PR completed faster.

# Additional Notes:

Any additional information that you think would be helpful when reviewing this PR.

Example:
* Does this change require documentation to be updated?
* Does this change add any new dependencies?
* Could this change or impact execution of existing code?

# Interested parties

Tag (@ mention) interested parties.

Thanks in advance for your help with the Archives Unleashed Toolkit!

### CODE REVIEW

**Comment by greebie** [comment]
I'll give this a test run today.  Overall it lgtm - it's just a matter of ensuring the RecordLoader works the same as last time (and based on the code, I see no reason why it should not).

**Comment by greebie** [comment]
Confirmed lgtm.  Tested with plain text extraction and WriteGEXF.  RecordLoader works as expected (as expected).

**Comment by greebie** [comment]
Tested with both arcs and warcs as well.

**Comment by lintool** [comment]
Taking a look at this - @helgeho what's the rationale for both an object `ArchiveRecord` and a trait `ArchiveRecord`?

**Comment by cjer** [comment]
AFAIK it's good practice to put (what would be in other languages) "static" methods (e.g. `ISO8601`) in a *companion object*, which is an object with the same name as the class or trait. It also has higher access privileges to that trait than other objects.

https://alvinalexander.com/scala/how-to-static-members-in-scala-companion-objects-fields-methods

**Comment by lintool** [comment]
Thanks for the info. In which case something like this should documented.

**Comment by greebie** [comment]
Flagging this to issue #176 for when I go through code documentation.

**Comment by helgeho** [comment]
@lintool, sorry about the confusion, but @cjer is correct, and that's why in my opinion this does *not* need to be documented, instead, anything that's not considered good practice should be documented, that's what we have design patterns and conventions for...

**Comment by lintool** [comment]
@helgeho I see.

Nevertheless, the rationale for turning `ArchiveRecord` into a trait should have been documented - for example, the PR template was never even filled out.

Plus, impl should really have been moved into it's own file.

**Comment by helgeho** [comment]
I asked @ruebot before, whether it would be okay to do so as the previous implementation was very inflexible with the `val`s instead of `def`s, I needed this flexibility for https://github.com/helgeho/ArchiveSpark-AUT-bridge. I kind of disagree with the own file, since this is the standard implementation and it's not java, but feel free to refactor that of course 🙂 I'll fill out the PR template next week as I am currently on vacation (writing this from my phone). Best, Helge

**Pull request merged**
